azure_storage_connectionstring: "DefaultEndpointsProtocol=https;AccountName=tryblobpythonfornow;AccountKey=ymjstVm2ggZe6cojZ/vKTrspF5yfdR6ZJMmxOmHakyWRsxwBx/5vrEKxKJIIE4lG4iGjYkrTxGTx+AStRszypA==;EndpointSuffix=core.windows.net"
file_container_name: "mycontainer"
source_folder: "C:/Users/NEL/Desktop/Reto/SISTEMAEMPLEADO/uploads/"
