name: Azure K8 Deploy
on: 
  workflow_dispatch:
env:
  REGISTRY_NAME: sistecreditoContainer
  CLUSTER_NAME: sistecredito
  CLUSTER_RESOURCE_GROUP: sistecreditoResourceGroup
  NAMESPACE: app
  APP_NAME: app.py
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Azure Blob Storage - Download Config
      uses: armanrahman22/azblob-download-action
      with:
        storage-account-name: "sistecredito"
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        container-name: "sistecredito"
        blob-name: ".env"
        download-path: "."
  
    # Container build and push to a Azure Container Registry (ACR)
    - name: Build Image
      run: docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Push Image in Registry
      run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
        dns-name-label: ${{ env.CLUSTER_RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
